CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    real_name VARCHAR(50),
    phone VARCHAR(20),
    id_card VARCHAR(32),
    email VARCHAR(100),
    dept_id BIGINT,
    status TINYINT DEFAULT 1,
    force_password_change TINYINT DEFAULT 0,
    failed_login_count INT DEFAULT 0,
    last_failed_login_at DATETIME,
    last_login_at DATETIME,
    last_login_ip VARCHAR(64),
    password_updated_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_count INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_failed_login_at DATETIME;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS id_card VARCHAR(32);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS force_password_change TINYINT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_ip VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_updated_at DATETIME;

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(255),
    project_code VARCHAR(100),
    bidding_agency VARCHAR(500),
    client_unit VARCHAR(255),
    registration_deadline DATETIME,
    bid_open_time VARCHAR(200),
    complaint_deadline VARCHAR(200),
    ceiling_price DECIMAL(15,2),
    floor_price DECIMAL(15,2),
    contract_payment VARCHAR(2000),
    qualifications CLOB,
    scoring_method CLOB,
    product_list CLOB,
    scoring_method_file VARCHAR(500),
    product_list_file VARCHAR(500),
    expert_composition VARCHAR(2000),
    price_score_method VARCHAR(2000),
    subjective_score_details VARCHAR(2000),
    bid_bond DECIMAL(15,2),
    performance_bond VARCHAR(500),
    text_length INT,
    page_count INT,
    markdown_file_path VARCHAR(500),
    file_path VARCHAR(500),
    file_original_name VARCHAR(255),
    uploader_id BIGINT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS extract_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(500),
    extract_type VARCHAR(50),
    text_length INT,
    response_length INT,
    success BOOLEAN,
    error_message CLOB,
    duration_ms INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prompt_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    content CLOB,
    field_def CLOB,
    is_active TINYINT DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS org_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    parent_id BIGINT,
    manager_user_id BIGINT,
    sort_order INT DEFAULT 0,
    status TINYINT DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE org_department ADD COLUMN IF NOT EXISTS manager_user_id BIGINT;

CREATE TABLE IF NOT EXISTS org_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    real_name VARCHAR(50),
    dept_id BIGINT,
    status TINYINT DEFAULT 1,
    last_login_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS org_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50),
    role_name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    status TINYINT DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE org_role ADD COLUMN IF NOT EXISTS role_code VARCHAR(50);

CREATE TABLE IF NOT EXISTS org_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS org_role_feature (
    role_id BIGINT NOT NULL,
    feature_code VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, feature_code)
);

CREATE TABLE IF NOT EXISTS org_role_data_scope (
    role_id BIGINT NOT NULL,
    module_code VARCHAR(50) NOT NULL,
    scope_rule VARCHAR(20) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, module_code)
);

CREATE TABLE IF NOT EXISTS org_role_field (
    role_id BIGINT NOT NULL,
    module_code VARCHAR(50) NOT NULL,
    field_code VARCHAR(50) NOT NULL,
    can_read TINYINT DEFAULT 1,
    can_write TINYINT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, module_code, field_code)
);

CREATE TABLE IF NOT EXISTS system_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_username VARCHAR(100),
    module VARCHAR(50),
    action VARCHAR(50),
    content VARCHAR(1000),
    request_method VARCHAR(20),
    request_path VARCHAR(255),
    ip VARCHAR(100),
    success TINYINT DEFAULT 1,
    error_message VARCHAR(1000),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_type VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    bucket VARCHAR(100),
    object_key VARCHAR(255) NOT NULL UNIQUE,
    original_name VARCHAR(255) NOT NULL,
    extension VARCHAR(50),
    content_type VARCHAR(100),
    file_size BIGINT DEFAULT 0,
    file_hash VARCHAR(128),
    storage_path VARCHAR(1000) NOT NULL,
    status TINYINT DEFAULT 1,
    uploader_id BIGINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_file_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL,
    biz_type VARCHAR(100) NOT NULL,
    biz_id BIGINT NOT NULL,
    category_code VARCHAR(100),
    sort_order INT DEFAULT 0,
    created_by BIGINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_system_file_status ON system_file(status);
CREATE INDEX IF NOT EXISTS idx_system_file_uploader ON system_file(uploader_id);
CREATE INDEX IF NOT EXISTS idx_system_file_created_at ON system_file(created_at);
CREATE INDEX IF NOT EXISTS idx_system_file_link_biz ON system_file_link(biz_type, biz_id);
CREATE INDEX IF NOT EXISTS idx_system_file_link_file_id ON system_file_link(file_id);

CREATE TABLE IF NOT EXISTS system_message (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    content_type VARCHAR(20) DEFAULT 'TEXT',
    message_type VARCHAR(50) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    biz_type VARCHAR(100),
    biz_id BIGINT,
    related_path VARCHAR(255),
    sender_id BIGINT,
    sender_name VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE system_message ADD COLUMN IF NOT EXISTS content_type VARCHAR(20) DEFAULT 'TEXT';
ALTER TABLE system_message ADD COLUMN IF NOT EXISTS biz_type VARCHAR(100);
ALTER TABLE system_message ADD COLUMN IF NOT EXISTS biz_id BIGINT;
ALTER TABLE system_message ADD COLUMN IF NOT EXISTS related_path VARCHAR(255);
UPDATE system_message SET content_type = 'TEXT' WHERE content_type IS NULL OR content_type = '';

CREATE TABLE IF NOT EXISTS system_message_receiver (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    message_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    receiver_type VARCHAR(20) DEFAULT 'TO',
    read_status TINYINT DEFAULT 0,
    read_at DATETIME,
    deleted_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_system_message_created_at ON system_message(created_at);
CREATE INDEX IF NOT EXISTS idx_system_message_receiver_user_id ON system_message_receiver(user_id);
CREATE INDEX IF NOT EXISTS idx_system_message_receiver_message_id ON system_message_receiver(message_id);
ALTER TABLE system_message_receiver ADD COLUMN IF NOT EXISTS receiver_type VARCHAR(20) DEFAULT 'TO';
DROP INDEX IF EXISTS uk_system_message_receiver_user;
CREATE UNIQUE INDEX IF NOT EXISTS uk_system_message_receiver_user_type ON system_message_receiver(message_id, user_id, receiver_type);
ALTER TABLE system_message_receiver ADD COLUMN IF NOT EXISTS deleted_at DATETIME;
UPDATE system_message_receiver SET receiver_type = 'TO' WHERE receiver_type IS NULL OR receiver_type = '';

CREATE TABLE IF NOT EXISTS system_todo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    content_type VARCHAR(20) DEFAULT 'TEXT',
    todo_type VARCHAR(50) NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    biz_type VARCHAR(100),
    biz_id BIGINT,
    assignee_id BIGINT NOT NULL,
    assignee_name VARCHAR(100),
    creator_id BIGINT,
    creator_name VARCHAR(100),
    due_at DATETIME,
    processed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_system_todo_assignee_id ON system_todo(assignee_id);
CREATE INDEX IF NOT EXISTS idx_system_todo_status ON system_todo(status);
CREATE INDEX IF NOT EXISTS idx_system_todo_due_at ON system_todo(due_at);
CREATE INDEX IF NOT EXISTS idx_system_todo_created_at ON system_todo(created_at);
CREATE INDEX IF NOT EXISTS idx_system_todo_biz ON system_todo(biz_type, biz_id);
ALTER TABLE system_todo ADD COLUMN IF NOT EXISTS content_type VARCHAR(20) DEFAULT 'TEXT';
UPDATE system_todo SET content_type = 'TEXT' WHERE content_type IS NULL OR content_type = '';

CREATE TABLE IF NOT EXISTS system_todo_assignee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL,
    assignee_id BIGINT NOT NULL,
    assignee_name VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    processed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_system_todo_assignee ON system_todo_assignee(todo_id, assignee_id);
CREATE INDEX IF NOT EXISTS idx_system_todo_assignee_user ON system_todo_assignee(assignee_id);
CREATE INDEX IF NOT EXISTS idx_system_todo_assignee_status ON system_todo_assignee(status);

INSERT INTO system_todo_assignee(todo_id, assignee_id, assignee_name, status, processed_at, created_at, updated_at)
SELECT t.id, t.assignee_id, t.assignee_name, t.status, t.processed_at,
       COALESCE(t.created_at, CURRENT_TIMESTAMP), COALESCE(t.updated_at, CURRENT_TIMESTAMP)
FROM system_todo t
WHERE t.assignee_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM system_todo_assignee a
      WHERE a.todo_id = t.id AND a.assignee_id = t.assignee_id
  );

CREATE TABLE IF NOT EXISTS system_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL UNIQUE,
    config_value CLOB,
    config_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    value_type VARCHAR(20) DEFAULT 'TEXT',
    group_code VARCHAR(50) DEFAULT 'basic',
    status TINYINT DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_dict_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code VARCHAR(100) NOT NULL UNIQUE,
    type_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sort_order INT DEFAULT 0,
    status TINYINT DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_dict_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id BIGINT NOT NULL,
    item_label VARCHAR(100) NOT NULL,
    item_value VARCHAR(100) NOT NULL,
    tag_color VARCHAR(50),
    sort_order INT DEFAULT 0,
    status TINYINT DEFAULT 1,
    is_default TINYINT DEFAULT 0,
    description VARCHAR(500),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_system_dict_item_type_id ON system_dict_item(type_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_system_dict_item_type_value ON system_dict_item(type_id, item_value);

INSERT INTO org_department (id, name, parent_id, sort_order, status)
SELECT 1, '我的公司', NULL, 0, 1
WHERE NOT EXISTS (SELECT 1 FROM org_department WHERE id = 1);

INSERT INTO org_role (id, role_code, role_name, description, status)
SELECT 1, 'admin', '系统管理员', '系统管理员', 1
WHERE NOT EXISTS (SELECT 1 FROM org_role WHERE id = 1);

INSERT INTO org_role (id, role_code, role_name, description, status)
SELECT 2, 'user', '普通用户', '普通用户', 1
WHERE NOT EXISTS (SELECT 1 FROM org_role WHERE id = 2);

UPDATE org_role SET role_code = role_name WHERE role_code IS NULL;
UPDATE org_role SET role_name = '系统管理员', description = '系统管理员' WHERE role_code = 'admin' AND role_name = 'admin';
UPDATE org_role SET role_name = '普通用户', description = '普通用户' WHERE role_code = 'user' AND role_name = 'user';

INSERT INTO org_user_role (user_id, role_id)
SELECT u.id, 1 FROM users u
WHERE u.role = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_user_role ur WHERE ur.user_id = u.id AND ur.role_id = 1);

INSERT INTO org_user_role (user_id, role_id)
SELECT u.id, 2 FROM users u
WHERE (u.role IS NULL OR u.role <> 'admin')
  AND NOT EXISTS (SELECT 1 FROM org_user_role ur WHERE ur.user_id = u.id AND ur.role_id = 2);

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_dict:read' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_dict:read');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_dict:create' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_dict:create');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_dict:import' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_dict:import');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_dict:update' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_dict:update');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_dict:export' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_dict:export');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_message:send' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_message:send');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_user:export' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_user:export');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_user:import' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_user:import');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_log:export' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_log:export');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_config:export' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_config:export');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_config:import' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_config:import');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_file:export' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_file:export');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_message:export' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_message:export');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_role:export' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_role:export');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_department:export' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_department:export');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_department:import' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_department:import');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_todo:read' FROM org_role r
WHERE r.role_code IN ('admin', 'user')
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_todo:read');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_todo:export' FROM org_role r
WHERE r.role_code IN ('admin', 'user')
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_todo:export');

INSERT INTO org_role_feature (role_id, feature_code)
SELECT r.id, 'system_todo:create' FROM org_role r
WHERE r.role_code = 'admin'
  AND NOT EXISTS (SELECT 1 FROM org_role_feature f WHERE f.role_id = r.id AND f.feature_code = 'system_todo:create');

DELETE FROM org_role_feature
WHERE feature_code NOT IN (
    'system_department:read',
    'system_department:create',
    'system_department:import',
    'system_department:update',
    'system_department:delete',
    'system_department:export',
    'system_department:manager',
    'system_user:read',
    'system_user:create',
    'system_user:import',
    'system_user:update',
    'system_user:export',
    'system_user:status',
    'system_user:password',
    'system_user:dept',
    'system_user:roles',
    'system_role:read',
    'system_role:create',
    'system_role:update',
    'system_role:delete',
    'system_role:export',
    'system_role:permission',
    'system_log:read',
    'system_log:export',
    'system_config:read',
    'system_config:import',
    'system_config:update',
    'system_config:export',
    'system_dict:read',
    'system_dict:create',
    'system_dict:import',
    'system_dict:update',
    'system_dict:export',
    'system_file:read',
    'system_file:upload',
    'system_file:download',
    'system_file:export',
    'system_file:delete',
    'system_file:link',
    'system_message:send'
    ,'system_message:export',
    'system_todo:read',
    'system_todo:create',
    'system_todo:export'
);

DELETE FROM org_role_data_scope
WHERE module_code <> 'system_user';

DELETE FROM org_role_field
WHERE NOT (
    (module_code = 'system_user' AND field_code IN ('username', 'realName', 'phone', 'idCard', 'email', 'dept', 'roles', 'status', 'forcePasswordChange', 'loginSecurity', 'lastLoginIp', 'passwordUpdatedAt'))
    OR (module_code = 'system_log' AND field_code IN ('operator', 'ip', 'request', 'content'))
);

INSERT INTO org_role_field (role_id, module_code, field_code, can_read, can_write, created_at, updated_at)
SELECT r.role_id, 'system_user', f.field_code, 1, f.can_write, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (SELECT DISTINCT role_id FROM org_role_field WHERE module_code = 'system_user') r
CROSS JOIN (
    SELECT 'phone' AS field_code, 1 AS can_write
    UNION ALL SELECT 'idCard', 1
    UNION ALL SELECT 'email', 1
    UNION ALL SELECT 'forcePasswordChange', 1
    UNION ALL SELECT 'loginSecurity', 0
    UNION ALL SELECT 'lastLoginIp', 0
    UNION ALL SELECT 'passwordUpdatedAt', 0
) f
WHERE 1 = 1
  AND NOT EXISTS (
      SELECT 1 FROM org_role_field existing
      WHERE existing.role_id = r.role_id
        AND existing.module_code = 'system_user'
        AND existing.field_code = f.field_code
  );

INSERT INTO org_role_field (role_id, module_code, field_code, can_read, can_write, created_at, updated_at)
SELECT r.role_id, 'system_log', 'request', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (SELECT DISTINCT role_id FROM org_role_field WHERE module_code = 'system_log') r
WHERE 1 = 1
  AND NOT EXISTS (
      SELECT 1 FROM org_role_field existing
      WHERE existing.role_id = r.role_id
        AND existing.module_code = 'system_log'
        AND existing.field_code = 'request'
  );

UPDATE org_role_field
SET can_write = 0, updated_at = CURRENT_TIMESTAMP
WHERE module_code = 'system_log'
  AND can_write <> 0;

UPDATE org_role_field
SET can_write = 0, updated_at = CURRENT_TIMESTAMP
WHERE module_code = 'system_user'
  AND field_code IN ('loginSecurity', 'lastLoginIp', 'passwordUpdatedAt')
  AND can_write <> 0;

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'enterprise.name', '我的公司', '企业名称', '用于部门树根节点等企业标识展示', 'TEXT', 'basic', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'enterprise.name');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'system.title', '投标管理系统', '系统标题', '用于系统标题展示', 'TEXT', 'basic', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'system.title');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'security.password.min_length', '6', '密码最小长度', '用户密码最小长度', 'NUMBER', 'security', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'security.password.min_length');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'security.password.require_strong', 'false', '强密码要求', '是否要求密码包含大小写、数字或特殊字符', 'BOOLEAN', 'security', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'security.password.require_strong');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'security.login.max_failed_attempts', '5', '登录失败次数上限', '连续登录失败次数达到上限后可用于触发安全策略', 'NUMBER', 'security', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'security.login.max_failed_attempts');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'security.session.timeout_minutes', '120', '登录有效时长', '登录会话默认有效时长，单位分钟', 'NUMBER', 'security', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'security.session.timeout_minutes');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'ui.default.page_size', '20', '默认分页条数', '列表页面默认每页条数', 'NUMBER', 'ui', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'ui.default.page_size');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'ui.page_size_options', '[10,20,50,100]', '分页条数选项', '列表页面可选分页条数', 'JSON', 'ui', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'ui.page_size_options');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'ui.sidebar.collapsed_default', 'false', '侧边栏默认收起', '进入系统时侧边栏是否默认收起', 'BOOLEAN', 'ui', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'ui.sidebar.collapsed_default');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'ui.watermark.enabled', 'false', '用户水印开关', '是否在后台页面显示用户水印', 'BOOLEAN', 'ui', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'ui.watermark.enabled');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'ui.watermark.text_template', '{realName} {username}', '用户水印模板', '支持占位符：{realName}、{username}、{systemTitle}、{dateTime}', 'TEXT', 'ui', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'ui.watermark.text_template');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'ui.watermark.opacity', '0.12', '用户水印透明度', '用户水印透明度，范围建议 0.05 - 0.2', 'NUMBER', 'ui', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'ui.watermark.opacity');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'ui.watermark.font_size', '16', '用户水印字号', '用户水印字号，单位 px，建议 12 - 24', 'NUMBER', 'ui', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'ui.watermark.font_size');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'ui.watermark.rotate', '-24', '用户水印旋转角度', '用户水印旋转角度，单位度，建议 -45 到 45', 'NUMBER', 'ui', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'ui.watermark.rotate');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'file.storage.type', 'LOCAL', '文件存储类型', '文件中心当前使用的存储类型，第一版默认本地存储', 'TEXT', 'basic', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'file.storage.type');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'file.local.base_path', 'uploads/files', '文件本地存储目录', '文件中心本地存储基础目录，相对路径默认以项目根目录为基准', 'TEXT', 'basic', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'file.local.base_path');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'file.upload.max_size_mb', '100', '文件上传大小限制', '文件中心单文件上传大小限制，单位 MB', 'NUMBER', 'basic', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'file.upload.max_size_mb');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'file.allowed_extensions', 'pdf,png,jpg,jpeg,gif,webp,bmp,svg,txt,md,doc,docx,xls,xlsx,ppt,pptx,zip,rar,7z', '允许上传扩展名', '文件中心允许上传的扩展名，多个用英文逗号分隔', 'TEXT', 'basic', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'file.allowed_extensions');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'file.previewable_extensions', 'pdf,png,jpg,jpeg,gif,webp,bmp,svg', '允许预览扩展名', '文件中心允许在线预览的扩展名，多个用英文逗号分隔', 'TEXT', 'basic', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'file.previewable_extensions');

INSERT INTO system_config (config_key, config_value, config_name, description, value_type, group_code, status)
SELECT 'message.default_page_size', '20', '消息中心默认分页大小', '消息中心默认分页大小', 'NUMBER', 'basic', 1
WHERE NOT EXISTS (SELECT 1 FROM system_config WHERE config_key = 'message.default_page_size');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'common_status', '通用启停状态', '基础平台通用启用/禁用状态', 10, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'common_status');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '启用', 'enabled', 'green', 10, 1, 1, '启用状态' FROM system_dict_type t
WHERE t.type_code = 'common_status'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'enabled');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '禁用', 'disabled', 'red', 20, 1, 0, '禁用状态' FROM system_dict_type t
WHERE t.type_code = 'common_status'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'disabled');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'success_status', '成功失败状态', '基础平台通用成功/失败结果', 20, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'success_status');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '成功', 'success', 'green', 10, 1, 1, '成功结果' FROM system_dict_type t
WHERE t.type_code = 'success_status'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'success');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '失败', 'failed', 'red', 20, 1, 0, '失败结果' FROM system_dict_type t
WHERE t.type_code = 'success_status'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'failed');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'user_role_type', '用户角色类型', '基础平台用户角色类型', 30, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'user_role_type');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '管理员', 'admin', 'gold', 10, 1, 0, '管理员角色' FROM system_dict_type t
WHERE t.type_code = 'user_role_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'admin');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '普通用户', 'user', 'arcoblue', 20, 1, 1, '普通用户角色' FROM system_dict_type t
WHERE t.type_code = 'user_role_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'user');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'config_group', '配置分组', '系统配置分组筛选项', 40, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'config_group');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '基础设置', 'basic', 'arcoblue', 10, 1, 1, '基础配置分组' FROM system_dict_type t
WHERE t.type_code = 'config_group'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'basic');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '安全设置', 'security', 'red', 20, 1, 0, '安全配置分组' FROM system_dict_type t
WHERE t.type_code = 'config_group'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'security');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '界面设置', 'ui', 'purple', 30, 1, 0, '界面配置分组' FROM system_dict_type t
WHERE t.type_code = 'config_group'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'ui');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'config_value_type', '配置值类型', '系统配置支持的值类型', 50, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'config_value_type');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'message_type', '消息类型', '站内消息中心消息类型', 55, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'message_type');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'todo_type', '待办类型', '待办中心待办类型', 56, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'todo_type');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'todo_priority', '待办优先级', '待办中心优先级', 57, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'todo_priority');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'todo_status', '待办状态', '待办中心状态', 58, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'todo_status');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '文本', 'TEXT', 'arcoblue', 10, 1, 1, '文本类型' FROM system_dict_type t
WHERE t.type_code = 'config_value_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'TEXT');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '数字', 'NUMBER', 'green', 20, 1, 0, '数字类型' FROM system_dict_type t
WHERE t.type_code = 'config_value_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'NUMBER');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '布尔', 'BOOLEAN', 'gold', 30, 1, 0, '布尔类型' FROM system_dict_type t
WHERE t.type_code = 'config_value_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'BOOLEAN');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, 'JSON', 'JSON', 'purple', 40, 1, 0, 'JSON 类型' FROM system_dict_type t
WHERE t.type_code = 'config_value_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'JSON');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '系统消息', 'SYSTEM', 'arcoblue', 10, 1, 1, '系统消息' FROM system_dict_type t
WHERE t.type_code = 'message_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'SYSTEM');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '公告通知', 'NOTICE', 'green', 20, 1, 0, '公告通知' FROM system_dict_type t
WHERE t.type_code = 'message_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'NOTICE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '待办提醒', 'TODO', 'gold', 30, 1, 0, '待办提醒' FROM system_dict_type t
WHERE t.type_code = 'message_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'TODO');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '风险预警', 'WARNING', 'orangered', 40, 1, 0, '风险预警' FROM system_dict_type t
WHERE t.type_code = 'message_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'WARNING');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '通用待办', 'GENERAL', 'arcoblue', 10, 1, 1, '通用待办类型' FROM system_dict_type t
WHERE t.type_code = 'todo_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'GENERAL');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '系统事项', 'SYSTEM', 'purple', 20, 1, 0, '系统事项待办' FROM system_dict_type t
WHERE t.type_code = 'todo_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'SYSTEM');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '跟进事项', 'FOLLOW_UP', 'green', 30, 1, 0, '跟进类待办' FROM system_dict_type t
WHERE t.type_code = 'todo_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'FOLLOW_UP');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '低', 'LOW', 'gray', 10, 1, 0, '低优先级' FROM system_dict_type t
WHERE t.type_code = 'todo_priority'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'LOW');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '中', 'MEDIUM', 'arcoblue', 20, 1, 1, '中优先级' FROM system_dict_type t
WHERE t.type_code = 'todo_priority'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'MEDIUM');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '高', 'HIGH', 'gold', 30, 1, 0, '高优先级' FROM system_dict_type t
WHERE t.type_code = 'todo_priority'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'HIGH');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '紧急', 'URGENT', 'red', 40, 1, 0, '紧急优先级' FROM system_dict_type t
WHERE t.type_code = 'todo_priority'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'URGENT');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '待处理', 'PENDING', 'red', 10, 1, 1, '待处理状态' FROM system_dict_type t
WHERE t.type_code = 'todo_status'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'PENDING');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '处理中', 'PROCESSING', 'gold', 20, 1, 0, '处理中状态' FROM system_dict_type t
WHERE t.type_code = 'todo_status'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'PROCESSING');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '已完成', 'DONE', 'green', 30, 1, 0, '已完成状态' FROM system_dict_type t
WHERE t.type_code = 'todo_status'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'DONE');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'tag_color', '标签颜色', '系统标签可选颜色', 60, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'tag_color');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'file_link_category', '文件关联分类', '文件中心业务关联分类', 61, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'file_link_category');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '蓝色', 'arcoblue', 'arcoblue', 10, 1, 1, 'Arco 蓝色标签' FROM system_dict_type t
WHERE t.type_code = 'tag_color'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'arcoblue');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '绿色', 'green', 'green', 20, 1, 0, '绿色标签' FROM system_dict_type t
WHERE t.type_code = 'tag_color'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'green');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '橙红', 'orangered', 'orangered', 30, 1, 0, '橙红标签' FROM system_dict_type t
WHERE t.type_code = 'tag_color'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'orangered');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '红色', 'red', 'red', 40, 1, 0, '红色标签' FROM system_dict_type t
WHERE t.type_code = 'tag_color'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'red');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '金色', 'gold', 'gold', 50, 1, 0, '金色标签' FROM system_dict_type t
WHERE t.type_code = 'tag_color'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'gold');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '紫色', 'purple', 'purple', 60, 1, 0, '紫色标签' FROM system_dict_type t
WHERE t.type_code = 'tag_color'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'purple');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '灰色', 'gray', 'gray', 70, 1, 0, '灰色标签' FROM system_dict_type t
WHERE t.type_code = 'tag_color'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'gray');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'file_storage_type', '文件存储类型', '文件中心存储方式', 65, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'file_storage_type');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '本地存储', 'LOCAL', 'arcoblue', 10, 1, 1, '本地磁盘存储' FROM system_dict_type t
WHERE t.type_code = 'file_storage_type'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'LOCAL');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '主文件', 'primary', 'arcoblue', 10, 1, 1, '业务对象主文件' FROM system_dict_type t
WHERE t.type_code = 'file_link_category'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'primary');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '附件', 'attachment', 'green', 20, 1, 0, '业务对象普通附件' FROM system_dict_type t
WHERE t.type_code = 'file_link_category'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'attachment');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '归档件', 'archive', 'purple', 30, 1, 0, '业务对象归档文件' FROM system_dict_type t
WHERE t.type_code = 'file_link_category'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'archive');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'operation_log_module', '操作日志模块', '操作日志模块筛选项', 70, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'operation_log_module');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '部门管理', 'DEPARTMENT', 'arcoblue', 10, 1, 0, '部门管理操作日志' FROM system_dict_type t
WHERE t.type_code = 'operation_log_module'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'DEPARTMENT');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '用户管理', 'USER', 'green', 20, 1, 0, '用户管理操作日志' FROM system_dict_type t
WHERE t.type_code = 'operation_log_module'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'USER');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '角色权限', 'ROLE', 'purple', 30, 1, 0, '角色权限操作日志' FROM system_dict_type t
WHERE t.type_code = 'operation_log_module'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'ROLE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '系统配置', 'CONFIG', 'gold', 40, 1, 0, '系统配置操作日志' FROM system_dict_type t
WHERE t.type_code = 'operation_log_module'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'CONFIG');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '字典管理', 'DICT', 'orangered', 50, 1, 0, '字典管理操作日志' FROM system_dict_type t
WHERE t.type_code = 'operation_log_module'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'DICT');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '登录认证', 'AUTH', 'gray', 60, 1, 0, '登录认证操作日志' FROM system_dict_type t
WHERE t.type_code = 'operation_log_module'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'AUTH');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '文件中心', 'FILE', 'purple', 70, 1, 0, '文件中心操作日志' FROM system_dict_type t
WHERE t.type_code = 'operation_log_module'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'FILE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '消息中心', 'MESSAGE', 'gold', 80, 1, 0, '消息中心操作日志' FROM system_dict_type t
WHERE t.type_code = 'operation_log_module'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'MESSAGE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '待办中心', 'TODO', 'orangered', 85, 1, 0, '待办中心操作日志' FROM system_dict_type t
WHERE t.type_code = 'operation_log_module'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'TODO');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '操作日志', 'LOG', 'gray', 90, 1, 0, '操作日志导出审计' FROM system_dict_type t
WHERE t.type_code = 'operation_log_module'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'LOG');

INSERT INTO system_dict_type (type_code, type_name, description, sort_order, status)
SELECT 'operation_log_action', '操作日志动作', '操作日志动作筛选项', 80, 1
WHERE NOT EXISTS (SELECT 1 FROM system_dict_type WHERE type_code = 'operation_log_action');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '新增', 'CREATE', 'green', 10, 1, 0, '新增操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'CREATE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '编辑', 'UPDATE', 'arcoblue', 20, 1, 0, '编辑操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'UPDATE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '删除', 'DELETE', 'red', 30, 1, 0, '删除操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'DELETE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '启用', 'ENABLE', 'green', 40, 1, 0, '启用操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'ENABLE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '禁用', 'DISABLE', 'red', 50, 1, 0, '禁用操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'DISABLE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '状态变更', 'STATUS', 'gold', 60, 1, 0, '状态变更操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'STATUS');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '导出', 'EXPORT', 'arcoblue', 65, 1, 0, '导出操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'EXPORT');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '导入', 'IMPORT', 'cyan', 67, 1, 0, '导入操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'IMPORT');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '重置密码', 'RESET_PASSWORD', 'gold', 70, 1, 0, '重置密码操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'RESET_PASSWORD');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '调部门', 'MOVE_DEPT', 'arcoblue', 80, 1, 0, '调整部门操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'MOVE_DEPT');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '分配角色', 'ASSIGN_ROLES', 'purple', 90, 1, 0, '分配角色操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'ASSIGN_ROLES');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '保存功能权限', 'SAVE_FEATURES', 'purple', 100, 1, 0, '保存功能权限操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'SAVE_FEATURES');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '保存数据范围', 'SAVE_DATA_SCOPE', 'purple', 110, 1, 0, '保存数据范围操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'SAVE_DATA_SCOPE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '保存字段权限', 'SAVE_FIELDS', 'purple', 120, 1, 0, '保存字段权限操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'SAVE_FIELDS');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '登录', 'LOGIN', 'green', 130, 1, 0, '登录操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'LOGIN');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '登录失败', 'LOGIN_FAILED', 'red', 132, 1, 0, '登录失败审计' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'LOGIN_FAILED');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '账号锁定', 'ACCOUNT_LOCKED', 'red', 134, 1, 0, '账号锁定审计' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'ACCOUNT_LOCKED');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '退出登录', 'LOGOUT', 'gray', 136, 1, 0, '退出登录审计' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'LOGOUT');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '修改个人密码', 'CHANGE_PASSWORD', 'gold', 137, 1, 0, '个人中心修改密码' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'CHANGE_PASSWORD');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '权限拒绝', 'PERMISSION_DENIED', 'red', 138, 1, 0, '权限拒绝审计' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'PERMISSION_DENIED');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '上传文件', 'UPLOAD', 'arcoblue', 140, 1, 0, '上传文件操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'UPLOAD');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '下载文件', 'DOWNLOAD', 'green', 142, 1, 0, '下载文件操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'DOWNLOAD');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '预览文件', 'PREVIEW', 'cyan', 144, 1, 0, '预览文件操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'PREVIEW');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '关联文件', 'LINK', 'purple', 146, 1, 0, '关联文件操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'LINK');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '解除关联', 'UNLINK', 'orangered', 148, 1, 0, '解除文件关联操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'UNLINK');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '发送消息', 'SEND', 'arcoblue', 150, 1, 0, '发送站内消息操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'SEND');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '阅读消息', 'READ', 'green', 152, 1, 0, '阅读站内消息操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'READ');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '全部已读', 'READ_ALL', 'purple', 154, 1, 0, '全部标记已读操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'READ_ALL');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '新增字典类型', 'CREATE_TYPE', 'green', 160, 1, 0, '新增字典类型操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'CREATE_TYPE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '编辑字典类型', 'UPDATE_TYPE', 'arcoblue', 170, 1, 0, '编辑字典类型操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'UPDATE_TYPE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '启用字典类型', 'ENABLE_TYPE', 'green', 180, 1, 0, '启用字典类型操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'ENABLE_TYPE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '禁用字典类型', 'DISABLE_TYPE', 'red', 180, 1, 0, '禁用字典类型操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'DISABLE_TYPE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '字典类型状态', 'STATUS_TYPE', 'gold', 190, 1, 0, '字典类型状态变更操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'STATUS_TYPE');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '新增字典项', 'CREATE_ITEM', 'green', 200, 1, 0, '新增字典项操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'CREATE_ITEM');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '编辑字典项', 'UPDATE_ITEM', 'arcoblue', 210, 1, 0, '编辑字典项操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'UPDATE_ITEM');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '启用字典项', 'ENABLE_ITEM', 'green', 220, 1, 0, '启用字典项操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'ENABLE_ITEM');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '禁用字典项', 'DISABLE_ITEM', 'red', 230, 1, 0, '禁用字典项操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'DISABLE_ITEM');

INSERT INTO system_dict_item (type_id, item_label, item_value, tag_color, sort_order, status, is_default, description)
SELECT t.id, '字典项状态', 'STATUS_ITEM', 'gold', 240, 1, 0, '字典项状态变更操作' FROM system_dict_type t
WHERE t.type_code = 'operation_log_action'
  AND NOT EXISTS (SELECT 1 FROM system_dict_item i WHERE i.type_id = t.id AND i.item_value = 'STATUS_ITEM');
